- .github/workflows/update-value.yml
- .github/workflows/values.template
- charts/agh2/templates/attack-frontend-deployment.yml
- charts/agh2/templates/attack-frontend-service.yml
- charts/agh2/templates/ingress.yml
- charts/agh2/values.yaml
Reverts Leukocyte-Lab/helm-charts#32
> Revert "fix: Use dash in app name will make helm parser falt."

- charts/agh2/README.md
docs: introduce that install agh with releaser act
> docs: introduce that install agh with releaser act

- charts/agh2/templates/base/agh-ingressroute.yml
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203584875518069
> feat: Add attack-ui redirect when only deploy attack.

- .github/workflows/values.template
- charts/agh2/Chart.yaml
- charts/agh2/templates/minio/agh-minio-users-secret.yml
- charts/agh2/values.yaml
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203917697477637
> fix: Must specify minio policy for core.

- charts/agh2/Chart.yaml
- charts/agh2/values.yaml
- perf: Increase max_connection to 32768 (default 100, previous 1024).
- perf: Increase shared_buffers to 4GB (default 128MB).
> perf: Tweak postgres default config.

- .github/workflows/auto-merge.yml
add dispatch agh2-update in Leukocyte-Lab/ArgusHack2 after AutoMerge UpdateHelmValue
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205295008390199
> feat(CI): dispatch agh2-update after AutoMerge UpdateHelmValue

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.0.1`
- App Version: `3.0.1`
- Captain: `v1.2.1`
- UI: `v1.0.4`
> build: Release chart/agh3 `v3.0.1`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.0.2`
- App Version: `3.0.2`
- Captain: `v1.2.1`
- UI: `v1.0.5`
> build: Release chart/agh3 `v3.0.2`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.0.3`
- App Version: `3.0.3`
- Captain: `v1.2.3`
- UI: `v1.0.5`
> build: Release chart/agh3 `v3.0.3`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.0.4`
- App Version: `3.0.4`
- Captain: `v1.3.0`
- UI: `v1.0.9`
> build: Release chart/agh3 `v3.0.4`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.0.5`
- App Version: `3.0.5`
- Captain: `v1.3.0`
- UI: `v1.0.10`
> build: Release chart/agh3 `v3.0.5`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.0.6`
- App Version: `3.0.6`
- Captain: `v1.3.1`
- UI: `v1.0.10`
> build: Release chart/agh3 `v3.0.6`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.0.7`
- App Version: `3.0.7`
- Captain: `v1.3.1`
- UI: `v1.0.11`
> build: Release chart/agh3 `v3.0.7`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.0.8`
- App Version: `3.0.8`
- Captain: `v1.3.1`
> build: Release chart/agh3 `v3.0.8`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.0.9`
- App Version: `3.0.9`
- Captain: `v1.3.2`
> build: Release chart/agh3 `v3.0.9`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.0.10`
- App Version: `3.0.10`
- Captain: `v1.3.3`
> build: Release chart/agh3 `v3.0.10`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.0.11`
- App Version: `3.0.11`
- Captain: `v1.3.4`
> build: Release chart/agh3 `v3.0.11`

- charts/agh3/Chart.yaml
- Chart Version: `3.1.0`
- App Version: `3.0.11`
- Captain: `v1.3.4`
> build: Release chart/agh3 `v3.1.0`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.2.0`
- App Version: `3.1.0`
- Captain: `v1.3.4`
- UI: `v1.1.0`
> build: Release chart/agh3 `v3.2.0`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.2.1`
- App Version: `3.1.1`
- Captain: `v1.3.5`
- UI: `v1.1.0`
> build: Release chart/agh3 `v3.2.1`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.2.2`
- App Version: `3.1.2`
- Captain: `v1.3.6`
- UI: `v1.1.0`
> build: Release chart/agh3 `v3.2.2`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.2.3`
- App Version: `3.1.3`
- Captain: `v1.3.7`
- UI: `v1.2.0`
> build: Release chart/agh3 `v3.2.3`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.2.4`
- App Version: `3.1.4`
- Captain: `v1.3.7`
- UI: `v1.2.1`
> build: Release chart/agh3 `v3.2.4`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.2.5`
- App Version: `3.1.5`
- Captain: `v1.3.8`
- UI: `v1.2.1`
> build: Release chart/agh3 `v3.2.5`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.2.6`
- App Version: `3.1.6`
- Captain: `v1.3.8`
- UI: `v1.2.2`
> build: Release chart/agh3 `v3.2.6`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.2.7`
- App Version: `3.1.7`
- Captain: `v1.3.8`
- UI: `v1.2.3`
> build: Release chart/agh3 `v3.2.7`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.2.8`
- App Version: `3.1.8`
- Captain: `v1.3.8`
- UI: `v1.2.4`
> build: Release chart/agh3 `v3.2.8`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.2.9`
- App Version: `3.1.9`
- Captain: `v1.4.0`
- UI: `v1.2.6`
> build: Release chart/agh3 `v3.2.9`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.3.0`
- App Version: `3.2.0`
- Captain: `v1.4.0`
- UI: `v1.2.7`
> build: Release chart/agh3 `v3.3.0`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.3.1`
- App Version: `3.2.1`
- Captain: `v1.4.1`
- UI: `v1.2.8`
> build: Release chart/agh3 `v3.3.1`

- charts/agh3/Chart.yaml
- Chart Version: `3.4.0`
- App Version: `3.2.1`
- Captain: `v1.4.1`
- UI: `v1.2.8`
> build: Release chart/agh3 `v3.4.0`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.4.1`
- App Version: `3.2.2`
- Captain: `v1.4.2`
- UI: `v1.2.8`
> build: Release chart/agh3 `v3.4.1`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.4.2`
- App Version: `3.2.3`
- Captain: `v1.4.4`
- UI: `v1.2.9`
> build: Release chart/agh3 `v3.4.2`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.4.3`
- App Version: `3.2.4`
- Captain: `v1.4.5`
- UI: `v1.2.9`
> build: Release chart/agh3 `v3.4.3`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.4.4`
- App Version: `3.2.5`
- Captain: `v1.4.5`
- UI: `v1.2.10`
> build: Release chart/agh3 `v3.4.4`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.4.5`
- App Version: `3.2.6`
- Captain: `v1.4.6`
- UI: `v1.2.11`
> build: Release chart/agh3 `v3.4.5`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.5.1`
- App Version: `3.3.1`
- Captain: `v1.5.2`
- UI: `v1.3.2`
___
___
- Updated chart version to `3.5.1` and application version to `v3.3.1` in `Chart.yaml`.
- Updated Captain image tag to `v1.5.2` and UI image tag to `v1.3.2` in `values.yaml`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump chart and application versions in Chart.yaml</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated chart version from <code>3.5.0</code> to <code>3.5.1</code>.<br> <li> Updated application version …
> build: Release chart/agh3 `v3.5.1`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.5.2`
- App Version: `3.3.2`
- Captain: `v1.5.3`
- UI: `v1.3.2`
___
___
- Updated the chart version to `3.5.2` in `Chart.yaml`.
- Updated the application version to `v3.3.2` in `Chart.yaml`.
- Updated the Captain image tag to `v1.5.3` in `values.yaml`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart and application versions in Chart.yaml</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated <code>version</code> from <code>3.5.1</code> to <code>3.5.2</code>.<br> <li> Updated …
> build: Release chart/agh3 `v3.5.2`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.5.3`
- App Version: `3.3.3`
- Captain: `v1.5.4`
- UI: `v1.3.2`
___
___
- Updated chart version to `3.5.3`.
- Updated app version to `v3.3.3`.
- Updated Captain image tag to `v1.5.4`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart and app versions in Chart.yaml</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated chart version from <code>3.5.2</code> to <code>3.5.3</code>.<br> <li> Updated app version from <code>v3.3.2</code> to …
> build: Release chart/agh3 `v3.5.3`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.5.4`
- App Version: `3.3.4`
- Captain: `v1.5.5`
- UI: `v1.3.4`
___
enhancement
___
- Updated chart version to `3.5.4` and application version to `v3.3.4` in `Chart.yaml`.
- Updated Captain image tag to `v1.5.5` and UI image tag to `v1.3.4` in `values.yaml`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart and application versions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated chart version from …
> build: Release chart/agh3 `v3.5.4`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.5.5`
- App Version: `3.3.5`
- Captain: `v1.5.6`
- UI: `v1.3.4`
___
___
- Updated chart version from `3.5.4` to `3.5.5` in `Chart.yaml`
- Updated app version from `v3.3.4` to `v3.3.5` in `Chart.yaml`
- Updated Captain image tag from `v1.5.5` to `v1.5.6` in `values.yaml`
___
<tr>
<td>
<details>
<hr>
<li>Updated chart version from …
> build: Release chart/agh3 `v3.5.5`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.5.6`
- App Version: `3.3.6`
- Captain: `v1.5.7`
- UI: `v1.3.4`
___
enhancement
___
- Updated chart version to `3.5.6` in `Chart.yaml`.
- Updated application version to `v3.3.6` in `Chart.yaml`.
- Updated Captain image tag to `v1.5.7` in `values.yaml`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump chart and application versions in Chart.yaml</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated chart version to <code>3.5.6</code>.<br> <li> Updated application version to <code>v3.3.6</code>.<br> …
> build: Release chart/agh3 `v3.5.6`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.5.7`
- App Version: `3.3.7`
- Captain: `v1.5.8`
- UI: `v1.3.4`
___
enhancement
___
- Bumped the chart version from `3.5.6` to `3.5.7` in `Chart.yaml`.
- Updated the application version from `v3.3.6` to `v3.3.7` in `Chart.yaml`.
- Updated the Captain image tag from `v1.5.7` to `v1.5.8` in `values.yaml`.
___
<tr>
<td>
<details>
<hr>
<li>Updated …
> build: Release chart/agh3 `v3.5.7`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.5.8`
- App Version: `3.3.8`
- Captain: `v1.5.8`
- UI: `v1.3.5`
___
___
- Updated chart version to `3.5.8`.
- Updated app version to `v3.3.8`.
- Updated UI image tag to `v1.3.5`.
___
<tr>
<td>
<details>
<hr>
<li>Updated chart version from <code>3.5.7</code> to <code>3.5.8</code>.<br> <li> Updated app version from <code>v3.3.7</code> to …
> build: Release chart/agh3 `v3.5.8`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.5.9`
- App Version: `3.3.9`
- UI: `v1.3.6`
- Report: `v1.0.3`
___
___
- Updated chart version to `3.5.9` and app version to `3.3.9` in `Chart.yaml`.
- Updated image tags in `values.yaml`:
- Captain image tag to `v1.5.9`
- UI image tag to `v1.3.6`
- Report image tag to `v1.0.3`
___
<tr>
<td>
<details>
<hr>
- Updated chart version to …
> build: Release chart/agh3 `v3.5.9`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.5.10`
- App Version: `3.3.10`
- UI: `v1.3.7`
- Report: `v1.0.4`
___
___
- Bumped chart version to `3.5.10` and application version to `v3.3.10` in `Chart.yaml`.
- Updated UI image tag to `v1.3.7` and report image tag to `v1.0.4` in `values.yaml`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump chart and application versions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated …
> build: Release chart/agh3 `v3.5.10`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.5.11`
- App Version: `3.3.11`
- UI: `v1.3.7`
- Report: `v1.0.5`
___
enhancement
___
- Updated chart version to `3.5.11` in `Chart.yaml`.
- Updated app version to `v3.3.11` in `Chart.yaml`.
- Updated report image tag to `v1.0.5` in `values.yaml`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart and app versions in Chart.yaml</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated chart version to <code>3.5.11</code>.<br> <li> Updated app version to …
> build: Release chart/agh3 `v3.5.11`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.5.12`
- App Version: `3.3.12`
- UI: `v1.3.7`
- Report: `v1.0.6`
___
enhancement
___
- Updated chart version to `3.5.12` in `Chart.yaml`.
- Updated app version to `v3.3.12` in `Chart.yaml`.
- Updated report image tag to `v1.0.6` in `values.yaml`.
___
<tr>
<td>
<details>
<hr>
<li>Updated chart version from <code>3.5.11</code> to <code>3.5.12</code>.<br> …
> build: Release chart/agh3 `v3.5.12`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.5.13`
- App Version: `3.3.13`
- UI: `v1.3.8`
___
enhancement
___
- Updated chart version to `3.5.13`
- Updated application version to `v3.3.13`
- Updated UI image tag to `v1.3.8`
- Updated Report image tag to `v1.0.9`
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump chart and application versions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated chart version to <code>3.5.13</code><br> …
> build: Release chart/agh3 `v3.5.13`

- charts/agh3/README.md
- charts/agh3/values.yaml
enhancement
___
- Updated default values for `postfix.mydomian`, `postfix.mail_myhostname`, and `postfix.domain` in `charts/agh3/values.yaml`.
___
<tr>
<td>
<details>
<summary><strong>values.yaml</strong><dd><code>Modify default postfix values in configuration file</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
charts/agh3/values.yaml
<li>Updated default values for <code>postfix.mydomian</code>, <code>postfix.mail_myhostname</code>, <br>and <code>postfix.domain</code>.<br>
</details>
</td>
<td><a href="https://github.com/Leukocyte-Lab/helm-charts/pull/191/files#diff-577b32ac773908f675673eed3b83bdda6951336585d398d0045b2896f64e8361">+3 …
> chore: Modify default postfix vaules.

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.6.0`
- App Version: `3.4.0`
- Captain: `v1.6.0`
- UI: `v1.5.1`
___
___
- Updated chart version to `3.6.0`.
- Updated application version to `v3.4.0`.
- Updated Captain image tag to `v1.6.0`.
- Updated UI image tag to `v1.5.1`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart and application versions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated chart version to <code>3.6.0</code>.<br> …
> build: Release chart/agh3 `v3.6.0`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.6.1`
- App Version: `3.4.1`
- Captain: `v1.6.1`
- UI: `v1.5.1`
___
enhancement
___
- Updated chart version to `3.6.1` in `Chart.yaml`.
- Updated application version to `v3.4.1` in `Chart.yaml`.
- Updated Captain image tag to `v1.6.1` in `values.yaml`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart and application versions in Chart.yaml</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated chart version to <code>3.6.1</code>.<br> <li> Updated application version to <code>v3.4.1</code>.<br>
</details>
</td> …
> build: Release chart/agh3 `v3.6.1`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.6.3`
- App Version: `3.4.2`
- Captain: `v1.6.3`
- UI: `v1.5.2`
___
___
- Updated chart version to `3.6.3` in `Chart.yaml`.
- Updated application version to `3.4.2` in `Chart.yaml`.
- Updated Captain image tag to `v1.6.3` in `values.yaml`.
- Updated UI image tag to `v1.5.2` in `values.yaml`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart and application versions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> build: Release chart/agh3 `v3.6.3`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.6.4`
- App Version: `3.4.3`
- Captain: `v1.6.4`
- UI: `v1.5.2`
___
enhancement
___
- Updated chart version to `3.6.4` in `Chart.yaml`.
- Updated app version to `v3.4.3` in `Chart.yaml`.
- Updated Captain image tag to `v1.6.4` in `values.yaml`.
___
<tr>
<td>
<details>
<hr>
<li>Updated chart version from <code>3.6.3</code> to <code>3.6.4</code><br> <li> …
> build: Release chart/agh3 `v3.6.4`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.6.5`
- App Version: `3.4.4`
- Captain: `v1.6.5`
- UI: `v1.5.3`
- Report: `v1.0.10`
___
___
- Updated chart version to `3.6.5` in `Chart.yaml`.
- Updated application version to `v3.4.4` in `Chart.yaml`.
- Updated Captain image tag to `v1.6.5` in `values.yaml`.
- Updated UI image tag to `v1.5.3` in `values.yaml`.
- Updated Report image tag to `v1.0.10` in `values.yaml`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart and application versions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> build: Release chart/agh3 `v3.6.5`

- .github/workflows/agh3-auto-release.yaml
This commit fix the issue that git config isn't run in git directory for the GitHub Action workflow for auto releasing Agh3.
___
Bug fix, Enhancement
___
- Moved the Git configuration steps to the 'Release Chart' section to ensure they are executed in the correct directory.
- Removed redundant Git configuration steps to streamline the workflow.
- Minor formatting adjustments for better readability.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>agh3-auto-release.yaml</strong><dd><code>Fix Git configuration in auto-release workflow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> Fix Auto Release AGH3

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
Reverts Leukocyte-Lab/helm-charts#203
___
enhancement
___
- Reverted chart version in `Chart.yaml` from `3.6.5` to `3.6.4`.
- Reverted app version in `Chart.yaml` from `v3.4.4` to `v3.4.3`.
- Reverted `captain` image tag in `values.yaml` from `v1.6.5` to `v1.6.4`.
- Reverted `ui` image tag in `values.yaml` from `v1.5.3` to `v1.5.2`.
- Reverted `report` image tag in `values.yaml` from `v1.0.10` to `v1.0.9`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Revert chart and app versions in Chart.yaml</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> Revert "build: Release chart/agh3 `v3.6.5`"

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.7.0`
- App Version: `3.5.0`
- Captain: `v1.7.1`
- UI: `v1.6.3`
- Report: `v1.1.1`
___
enhancement, configuration changes
___
- Updated the chart version to `3.7.0` and the application version to `v3.5.0` in `Chart.yaml`.
- Updated image tags for the following components in `values.yaml`:
- Captain: `v1.7.1`
- UI: `v1.6.3`
- Report: `v1.1.1`
- Removed unnecessary blank lines in `values.yaml`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart and application versions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> build: Release chart/agh3 `v3.7.0`

- charts/agh3/templates/captain/captain-deployment.yml
- charts/agh3/templates/controller/controller-deployment.yml
Bug fix
___
- Added conditional logic to include proxy environment variables in Captain and Controller deployments based on the `global.proxy.enabled` value.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>captain-deployment.yml</strong><dd><code>Respect proxy enabled value in Captain deployment</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
charts/agh3/templates/captain/captain-deployment.yml
<li>Added conditional inclusion of proxy environment variables based on <br><code>global.proxy.enabled</code> value.<br>
</details>
</td>
<td><a href="https://github.com/Leukocyte-Lab/helm-charts/pull/211/files#diff-6dfdd2c92837e5a09203b6356a …
> fix: Should respect proxy enabled value.

- charts/agh3/Chart.yaml
- Chart Version: `3.7.1`
- App Version: `3.5.0`
- Captain: `v1.7.1`
- UI: `v1.6.3`
- Report: `v1.1.1`
___
enhancement
___
- Updated chart version in `charts/agh3/Chart.yaml` from `3.7.0` to `3.7.1`
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump chart version to 3.7.1</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated chart version from `3.7.0` to `3.7.1`
</details>
</td>
<td><a …
> build: Release chart/agh3 `v3.7.1`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.7.2`
- App Version: `3.5.0`
- Captain: `v1.7.2`
- UI: `v1.6.3`
- Report: `v1.1.1`
___
___
- Updated chart version in `Chart.yaml` from `3.7.1` to `3.7.2`.
- Updated Captain image tag in `values.yaml` from `v1.7.1` to `v1.7.2`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump chart version to 3.7.2</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated chart …
> build: Release chart/agh3 `v3.7.2`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.7.4`
- App Version: `3.5.2`
- Captain: `v1.7.4`
- UI: `v1.6.8`
- Report: `v1.1.3`
___
___
- Updated chart version to `3.7.4` and application version to `v3.5.2`.
- Updated image tags for Captain (`v1.7.4`), UI (`v1.6.8`), and Report (`v1.1.3`).
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump chart and application versions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated chart version from …
> build: Release chart/agh3 `v3.7.4`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.7.5`
- App Version: `3.5.3`
- Captain: `v1.7.5`
- UI: `v1.6.10`
___
___
- Updated chart version to `3.7.5` and app version to `v3.5.3` in `Chart.yaml`.
- Updated image tags in `values.yaml`:
- Captain image tag updated to `v1.7.5`
- UI image tag updated to `v1.6.10`
- Report image tag updated to `v1.1.4`
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart and app versions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> build: Release chart/agh3 `v3.7.5`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.7.6`
- App Version: `3.5.4`
- Captain: `v1.7.6`
- UI: `v1.6.10`
___
___
- Bumped chart version from `3.7.5` to `3.7.6` in `Chart.yaml`.
- Updated app version from `v3.5.3` to `v3.5.4` in `Chart.yaml`.
- Updated Captain image tag from `v1.7.5` to `v1.7.6` in `values.yaml`.
___
<tr>
<td>
<details>
<hr>
<li>Updated chart version from …
> build: Release chart/agh3 `v3.7.6`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.7.8`
- App Version: `3.5.6`
- Captain: `v1.7.6`
- UI: `v1.6.12`
> build: Release chart/agh3 `v3.7.8`

- charts/agh3/templates/captain/captain-deployment.yml
- charts/agh3/values.yaml
enhancement, configuration changes
___
- Added `KEYGEN_URL` environment variable to the Captain deployment, sourced from a Kubernetes secret.
- Created a new Kubernetes Secret template for Keygen, including a `url` field for the Keygen API URL.
- Updated `values.yaml` to include configuration parameters for the Keygen secret, such as enabling the secret, setting the secret name, and specifying the Keygen API URL.
___
<tr>
<td>
<details>
<summary><strong>captain-deployment.yml</strong><dd><code>Add `KEYGEN_URL` environment variable to Captain deployment</code></dd></summary>
<hr>
charts/agh3/templates/captain/captain-deployment.yml
<li>Added …
> feat: add keygen url env

- .github/workflows/postfix.yml
enhancement
___
- Enhanced the CI workflow for Postfix by updating the `actions/checkout` version and adding new steps for packaging Helm charts.
- Improved Git configuration for better release management.
- Streamlined the process of adding Helm dependencies and releasing charts.
___
<tr>
<td>
<details>
<summary><strong>postfix.yml</strong><dd><code>Update Postfix CI Workflow for Helm Chart Management</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/postfix.yml
<li>Updated <code>actions/checkout</code> from v2 to v4.<br> <li> Added steps for packaging Helm charts.<br> <li> Improved Git configuration for releases.<br> <li> …
> ci: update postfix release ci

- charts/agh3/Chart.yaml
- Chart Version: `3.7.9`
- App Version: `3.5.6`
- Captain: `v1.7.6`
- UI: `v1.6.12`
___
enhancement
___
- Updated the chart version to `3.7.9` to reflect the latest changes.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart version to 3.7.9</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated chart version from `3.7.8` to `3.7.9`.
</details>
</td>
<td><a …
> build: Release chart/agh3 `v3.7.9`

- charts/playground/Chart.yaml
- charts/playground/values.yaml
- Chart Version: `1.1.0`
- App Version: `1.1.0`
- Playground: `v1.1.0`
___
enhancement
___
- Released chart for `agh3-playground` version `1.1.0`.
- Updated chart version and application version to `1.1.0`.
- Updated Playground image tag to `v1.1.0`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update Chart and App Versions to 1.1.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
charts/playground/Chart.yaml
<li>Updated chart version from <code>1.0.1</code> to <code>1.1.0</code>.<br> <li> Updated app version from …
> build: Release chart/agh3-playground `v1.1.0`

- charts/agh3/values.yaml
enhancement
___
- Introduced a new `architecture` parameter for Redis to specify its mode.
- Configured Redis to operate in `standalone` mode for improved deployment flexibility.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>values.yaml</strong><dd><code>Update Redis configuration to standalone architecture</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
charts/agh3/values.yaml
<li>Added <code>architecture</code> parameter for Redis configuration.<br> <li> Set <code>architecture</code> to <code>standalone</code>.<br>
</details>
</td>
<td><a href="https://github.com/Leukocyte-Lab/helm-charts/pull/230/files#diff-577b32ac773908f675673eed3b83bdda69 …
> build: Change redis to standalone mode.

- charts/playground/Chart.yaml
- charts/playground/values.yaml
- Chart Version: `1.2.0`
- App Version: `1.2.0`
- Playground: `v1.2.0`
___
enhancement
___
- Released chart version `1.2.0` for the playground application.
- Updated application version to `1.2.0`.
- Updated the playground image tag to `v1.2.0`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update Chart and App Versions to 1.2.0</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
charts/playground/Chart.yaml
<li>Updated chart version from <code>1.1.0</code> to <code>1.2.0</code>.<br> <li> Updated app version from …
> build: Release chart/agh3-playground `v1.2.0`

- charts/agh3/Chart.lock
- charts/agh3/Chart.yaml
- charts/agh3/templates/report/report-deployment.yml
- charts/agh3/templates/report/report-service.yml
- charts/agh3/values.yaml
- **fix: pgroonga is not used in agh3 #200**
- **fix: should be disable report #199**
- **build: upgrade minio chart and version**
___
enhancement, bug fix
___
- Upgraded `minio` dependency to version `14.7.15`.
- Fixed report deployment and service templates to use `.Values.report.enabled` instead of `.Values.ui.enabled`.
- Updated PostgreSQL image repository and tag for better compatibility.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Upgrade `minio` dependency version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> build(deps): Update dependencies charts

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.8.0`
- App Version: `3.6.0`
- Captain: `v1.8.0`
- UI: `v1.7.3`
___
Enhancement
___
- Updated the chart version to `3.8.0` and app version to `3.6.0`.
- Updated the Captain image tag to `v1.8.0`.
- Updated the UI image tag to `v1.7.3`.
___
<tr>
<td>
<details>
<hr>
- Updated chart version to `3.8.0`
- Updated app version to `3.6.0`
</details>
</td>
<td><a …
> build: Release chart/agh3 `v3.8.0`

- charts/playground/Chart.yaml
- Chart Version: `1.2.1`
- App Version: `1.2.0`
- Playground: `v1.2.0`
___
enhancement
___
- Updated the chart version to `1.2.1` to reflect the latest changes.
- Maintains the application version at `1.2.0`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart version to 1.2.1</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
charts/playground/Chart.yaml
- Updated the chart version from `1.2.0` to `1.2.1`.
</details>
</td>
<td><a …
> build: Release chart/agh3-playground `v1.2.1`

- charts/agh3/Chart.yaml
- Chart Version: `3.8.1`
- App Version: `3.6.0`
- Captain: `v1.8.0`
- UI: `v1.7.3`
___
enhancement
___
- Updated the chart version to `3.8.1` to reflect the latest changes.
- Maintained the application version at `3.6.0` with no changes to dependencies.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update chart version to 3.8.1</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
- Updated chart …
> build: Release chart/agh3 `v3.8.1`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.8.2`
- App Version: `3.6.1`
- Captain: `v1.8.1`
- UI: `v1.7.3`
___
enhancement
___
- Released chart version `3.8.2` with updated application version.
- Updated Captain image tag to the latest version.
___
<tr>
<td>
<details>
<hr>
<li>Updated chart version from <code>3.8.1</code> to <code>3.8.2</code><br> <li> Updated app version from <code>v3.6.0</code> to …
> build: Release chart/agh3 `v3.8.2`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.8.3`
- App Version: `3.6.2`
- Captain: `v1.8.2`
- UI: `v1.7.3`
___
enhancement
___
- Released chart version `3.8.3` with updated application version.
- Updated Captain image tag to the latest version.
___
<tr>
<td>
<details>
<hr>
<li>Updated chart version from <code>3.8.2</code> to <code>3.8.3</code>.<br> <li> Updated app version from <code>v3.6.1</code> to …
> build: Release chart/agh3 `v3.8.3`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.8.5`
- App Version: `3.6.4`
- Captain: `v1.8.3`
- UI: `v1.7.4`
___
enhancement
___
- Updated the chart version to `3.8.5` and the app version to `3.6.4`.
- Changed the UI image tag to `v1.7.4`.
___
<tr>
<td>
<details>
<hr>
<li>Updated chart version from <code>3.8.4</code> to <code>3.8.5</code><br> <li> Updated app version from <code>v3.6.3</code> to …
> build: Release chart/agh3 `v3.8.5`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.8.6`
- App Version: `3.6.5`
- Captain: `v1.8.3`
- UI: `v1.7.5`
___
enhancement
___
- Updated the chart version to `3.8.6` and app version to `3.6.5`.
- Updated the UI image tag to `v1.7.5`.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update Chart and App Versions to 3.8.6 and 3.6.5</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated chart version from <code>3.8.5</code> to <code>3.8.6</code><br> <li> Updated app version from <code>v3.6.4</code> to <code>v3.6.5</code><br>
</details>
</td>
<td><a …
> build: Release chart/agh3 `v3.8.6`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.8.7`
- App Version: `3.6.6`
- Captain: `v1.8.4`
- UI: `v1.7.5`
___
enhancement
___
- Released chart version `3.8.7` with updated application version `3.6.6`.
- Updated Captain image tag to `v1.8.4` for improved functionality.
___
<tr>
<td>
<details>
<hr>
<li>Updated chart version from <code>3.8.6</code> to <code>3.8.7</code><br> <li> Updated app version from …
> build: Release chart/agh3 `v3.8.7`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.8.8`
- App Version: `3.6.7`
- Captain: `v1.8.5`
- UI: `v1.7.5`
___
Enhancement
___
- Released chart version `3.8.8` with updated application version `3.6.7`.
- Updated Captain image tag to `v1.8.5`.
___
<tr>
<td>
<details>
<hr>
<li>Updated chart version from <code>3.8.7</code> to <code>3.8.8</code><br> <li> Updated app version from <code>v3.6.6</code> to …
> build: Release chart/agh3 `v3.8.8`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.8.9`
- App Version: `3.6.8`
- Captain: `v1.8.6`
- UI: `v1.8.0`
___
Enhancement
___
- Updated the chart version to `3.8.9` and app version to `3.6.8`.
- Updated the Captain image tag to `v1.8.6` and UI image tag to `v1.8.0`.
___
<tr>
<td>
<details>
<hr>
<li>Updated chart version from <code>3.8.8</code> to <code>3.8.9</code>.<br> <li> Updated app version from …
> build: Release chart/agh3 `v3.8.9`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.8.10`
- App Version: `3.6.9`
- Captain: `v1.8.7`
- UI: `v1.8.0`
___
enhancement
___
- Released chart version `3.8.10` with updated application version.
- Updated dependencies for Captain and UI image tags to their latest versions.
___
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Update Chart and App Versions to 3.8.10</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<li>Updated chart version from <code>3.8.9</code> to <code>3.8.10</code><br> <li> …
> build: Release chart/agh3 `v3.8.10`

- charts/playground/Chart.yaml
Reverts Leukocyte-Lab/helm-charts#235
> Revert "build: Release chart/agh3-playground `v1.2.1`"

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.9.0`
- App Version: `3.7.0`
- Captain: `v1.9.0`
- UI: `v1.8.1`
___
enhancement
___
- Released chart version `3.9.0` with updated application versions.
- Updated Captain to version `v1.9.0` and UI to version `v1.8.1`.
- Ensured compatibility with the latest dependencies.
___
<tr>
<td>
<details>
<hr>
<li>Updated chart version from <code>3.8.12</code> to …
> build: Release chart/agh3 `v3.9.0`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.10.4`
- App Version: `3.8.4`
- Captain: `v1.10.7`
- Controller: `v1.0.0-beta`
- UI: `v1.10.5`
> build: Release chart/agh3 `v3.10.4`

- charts/agh3/Chart.yaml
- charts/agh3/values.yaml
- Chart Version: `3.11.12`
- App Version: `3.10.7`
- ActionLoop: `v1.14.6`
- Captain: `v1.14.6`
- Controller: `v1.0.0`
- UI: `v1.12.12`
> build: Release chart/agh3 `v3.11.12`

- charts/playground/Chart.yaml
- charts/playground/values.yaml
- Chart Version: `1.6.8`
- App Version: `1.6.8`
- Playground: `v1.6.8`
> build: Release chart/agh3-playground `v1.6.8`
